default: &default
  working_directory: ~/repo
  docker:
    - image: circleci/openjdk:8-jdk
version: 2
jobs:
  code_checkout:
    <<: *default
    steps:
      - checkout
      - save_cache:
          key: repo-1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/repo
  resolve_dependencies:
    <<: *default
    steps:
      - restore_cache:
          keys:
            - repo-1-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Resolve Dependencies
          command: mvn dependency:resolve
      - save_cache:
          paths:
            - ~/.m2
          key: repo-1-dependency-{{ .Branch }}-{{ .Revision }}
  build:
    <<: *default
    steps:
      - restore_cache:
          keys:
            - repo-1-{{ .Branch }}-{{ .Revision }}
            - repo-1-dependency-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Build project
          command: mvn clean install -DskipTests
      - save_cache:
          key: repo-1-target-{{ .Branch }}-{{ .Revision }}
          paths:
            - target/
  test:
    <<: *default
    steps:
      - restore_cache:
          keys:
            - repo-1-{{ .Branch }}-{{ .Revision }}
            - repo-1-dependencies-{{ .Branch }}-{{ .Revision }}
            - repo-1-target-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Install Chrome
          command: |
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
            sudo apt-get update
            sudo apt-get install google-chrome-stable
      - run:
          name: Make driver executable
          command: |
            pwd
            ls
            chmod +x target/classes/drivers/linux/chromedriver
      - run:
          name: Run Tests with Sonar Coverage
          command: mvn org.jacoco:jacoco-maven-plugin:prepare-agent install -Pcoverage-per-test
      - save_cache:
          key: repo-1-reports-{{ .Branch }}-{{ .Revision }}
          paths:
            - reports/
  code_analysis:
    <<: *default
    steps:
      - restore_cache:
          keys:
            - repo-1-{{ .Branch }}-{{ .Revision }}
            - repo-1-dependencies-{{ .Branch }}-{{ .Revision }}
            - repo-1-target-{{ .Branch }}-{{ .Revision }}
            - repo-1-reports-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Update Sonar Analysis
          command: mvn package sonar:sonar -Dsonar.host.url=$SONAR_HOST -Dsonar.organization=$SONAR_ORG -Dsonar.login=$SONAR_KEY

filters: &all_branches
  branches:
    only:
      - develop
      - master
      - release
      - /issue-.*/

workflows:
  version: 2
  normal_flow:
    jobs:
      - code_checkout:
          filters: *all_branches
      - resolve_dependencies:
          filters: *all_branches
          requires:
            - code_checkout
      - build:
          filters: *all_branches
          requires:
            - resolve_dependencies
      - test:
          requires:
            - build
          filters: *all_branches
      - code_analysis:
          requires:
            - test
          filters: *all_branches
